import './globals.css'
import { ReduxProvider } from '@/redux/Provider'


export const metadata = {
  title: 'Shoes Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
